name: Somativa 2 - Devops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      - name: Build
        run: echo "Build ok"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install Flask
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"


  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t wbotta/wallacesomativa2:latest .

      - name: Push na imagem do Docker
        run: docker push wbotta/wallacesomativa2:latest

      - name: Enviar a notifação para o Discord
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' -d '{"content":"Notificação recebida!"}' "${{ env.DISCORD_WEBHOOK }}"

