name: Somativa 2 - Devops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      - name: Build
        run: echo "Build concluído com sucesso!"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install Flask
      - name: Run SAST test
        uses: shiftleftsecurity/sast-scan@v2.1.1
        with:
          language: python
          scan-path: .
          fail-on-error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in no Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t wbotta/wallacesomativa2:latest .

      - name: Push Docker image
        run: docker push wbotta/wallacesomativa2:latest

      - name: Send notification
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"content": "Uma nova imagem Docker foi publicada!"}' \
            $DISCORD_WEBHOOK
